Implementation of CP Decomposition
jturney/EinsumsInCpp pull request #3
Opened 2022-06-08 19:13 UTC by andyj10224

This code allows the decomposition of an arbitrary dimensional tensor into a sum of outer products of vectors (called candecomp, or CP, decomposition)

(i.e. `X[i][j][k] = \sum_{r} (a[i][r] * b[j][r] * c[k][r]`)

2022-06-08 20:30 UTC, jturney requested changes
Nice work!

Just a couple of changes to be made.

2022-06-08 20:30 UTC, jturney commented on src/include/einsums/Decomposition.hpp
> +using namespace einsums::tensor_algebra::index;
Since this is a header file, let's move the `using namespace`s to be inside the functions that need them and not in global scope.

2022-06-08 20:30 UTC, jturney commented on src/include/einsums/Decomposition.hpp
> +    std::vector<Tensor<2, TType>> unfolded_matrices;
Not to be done now, but something to think about: If we're decomposing a large tensor do we want to have all unfolds precomputed? That could consume a lot of memory.

2022-06-09 13:19 UTC, andyj10224 commented on src/include/einsums/Decomposition.hpp
> +    std::vector<Tensor<2, TType>> unfolded_matrices;
I thought the same thing, but I have not been able to get my code to work without this approach (likely due to issues involving reallocating a tensor previously computed). Could you help me with that?

2022-06-09 13:26 UTC, andyj10224 commented on src/include/einsums/Decomposition.hpp
> +using namespace einsums::tensor_algebra::index;
Done

2022-06-09 14:04 UTC, andyj10224 commented on src/include/einsums/Decomposition.hpp
> +    std::vector<Tensor<2, TType>> unfolded_matrices;
Fixed (used some low level C++)

2022-06-10 14:58 UTC, merged